plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id("com.github.ben-manes.versions") version "0.53.0"
}

group = 'io.github.jinahya'
version = '0.0.1-SNAPSHOT'
description = 'Rick and Morty API Spring Data Rest'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenLocal() // when testing against a SNAPSHOT
    mavenCentral()
}

dependencies {
    implementation 'io.github.jinahya:rickandmortyapi-persistence:0.1.6'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-hateoas' // required by springdoc-openapi

    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-rest-test'
    implementation 'org.springframework.data:spring-data-rest-hal-explorer'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    testImplementation 'org.springframework.boot:spring-boot-starter-test' // ?

    runtimeOnly 'org.hibernate.orm:hibernate-community-dialects'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    runtimeOnly 'org.xerial:sqlite-jdbc:3.51.1.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
